### ISSUE TITLE
NameError: uninitialized constant Exhaust::Runner::Timeout

### ISSUE THREAD

**Issue by dfriquet** [mwoods79/exhaust#3]
Hello there,

This gem is the perfect match for what I need, but it's been almost three years without any activity so far… As I get "trivial errors" out-of-the-box, I was just wondering if it is still in use anywhere on projects currently in progress? If it's not, what alternatives have you found?

I really want to _user-acceptance test_ my EmberJS app against the real Rails API server. I tried out the _Mirage approach_; eventually, they couldn't have named it better – a mirage, but not in a good way.

Big question: should I spend a fair amount of energy fixing a three years old Exhaust, or use anything already doing the job I haven't found yet?

Thanks!

**Comment by mwoods79** [comment]
Hi @dfriquet :wave:,

I really don't maintain this anymore. Feel free to modify it. The gem is simple, it opens a pipe for `rails serve` and opens a pipe for `ember-cli start`. This allows you to load your own rails environment in the appropriate place.

```
ENV['RAILS_ENV'] ||= 'test'
path_to_rails = "/path/to/rails"
require File.expand_path("#{path_to_rails}/config/environment")
```

I imagine your problems are coming from your configuration and not from this gem. However, if you discover that your issues are generated by this gem, feel free to make a pull request, there is very little code and hopefully it easy to understand.

Unfortunately, there still isn't a great way to integration test your whole app. This still may be your best bet. If you come up with a good/clever solution please let me know.
